const items = {
    survivors: [
        {name: "Acrid", sotv: false, sots: false, image: "images/survivors/Acrid.webp"},
        {name: "Artificer", sotv: false, sots: false, image: "images/survivors/Artificer.webp"},
        {name: "Bandit", sotv: false, sots: false, image: "images/survivors/Bandit.webp"},
        {name: "Captain", sotv: false, sots: false, image: "images/survivors/Captain.webp"},
        {name: "Chef", sotv: false, sots: true, image: "images/survivors/CHEF.webp"},
        {name: "Commando", sotv: false, sots: false, image: "images/survivors/Commando.webp"},
        {name: "Engineer", sotv: false, sots: false, image: "images/survivors/Engineer.webp"},
        {name: "False Son", sotv: false, sots: true, image: "images/survivors/False_Son.webp"},
        {name: "Heretic", sotv: false, sots: false, image: "images/survivors/Heretic.webp"},
        {name: "Huntress", sotv: false, sots: false, image: "images/survivors/Huntress.webp"},
        {name: "Loader", sotv: false, sots: false, image: "images/survivors/Loader.webp"},
        {name: "Mercenary", sotv: false, sots: false, image: "images/survivors/Mercenary.webp"},
        {name: "MUL-T", sotv: false, sots: false, image: "images/survivors/MUL-T.webp"},
        {name: "Railgunner", sotv: true, sots: false, image: "images/survivors/Railgunner.webp"},
        {name: "Seeker", sotv: false, sots: true, image: "images/survivors/Seeker.webp"},
        {name: "REX", sotv: false, sots: false, image: "images/survivors/REX.webp"},
        {name: "Void Fiend", sotv: true, sots: false, image: "images/survivors/Void_Fiend.webp"}
    ],
    white: [
        {name: "Armor-Piercing Rounds", sotv: false, sots: false, image: "images/itemsWhite/Armor-Piercing_Rounds.webp"},
        {name: "Backup Magazine", sotv: false, sots: false, image: "images/itemsWhite/Backup_Magazine.webp"},
        {name: "Bison Steak", sotv: false, sots: false, image: "images/itemsWhite/Bison_Steak.webp"},
        {name: "Bolstering Lantern", sotv: false, sots: true, image: "images/itemsWhite/Bolstering_Lantern.webp"},
        {name: "Bundle of Fireworks", sotv: false, sots: false, image: "images/itemsWhite/Bundle_of_Fireworks.webp"},
        {name: "Bustling Fungus", sotv: false, sots: false, image: "images/itemsWhite/Bustling_Fungus.webp"},
        {name: "Cautious Slug", sotv: false, sots: false, image: "images/itemsWhite/Cautious_Slug.webp"},
        {name: "Chronic Expansion", sotv: false, sots: true, image: "images/itemsWhite/Chronic_Expansion.webp"},
        {name: "Crowbar", sotv: false, sots: false, image: "images/itemsWhite/Crowbar.webp"},
        {name: "Delicate Watch", sotv: true, sots: false, image: "images/itemsWhite/Delicate_Watch.webp"},
        {name: "Elusive Antlers", sotv: false, sots: true, image: "images/itemsWhite/Elusive_Antlers.webp"},
        {name: "Energy Drink", sotv: false, sots: false, image: "images/itemsWhite/Energy_Drink.webp"},
        {name: "Focus Crystal", sotv: false, sots: false, image: "images/itemsWhite/Focus_Crystal.webp"},
        {name: "Gasoline", sotv: false, sots: false, image: "images/itemsWhite/Gasoline.webp"},
        {name: "Item Scrap, White", sotv: false, sots: false, image: "images/itemsWhite/Item_Scrap,_White.webp"},
        {name: "Lens-Maker's Glasses", sotv: false, sots: false, image: "images/itemsWhite/Lens-Maker's_Glasses.webp"},
        {name: "Medkit", sotv: false, sots: false, image: "images/itemsWhite/Medkit.webp"},
        {name: "Mocha", sotv: true, sots: false, image: "images/itemsWhite/Mocha.webp"},
        {name: "Monster Tooth", sotv: false, sots: false, image: "images/itemsWhite/Monster_Tooth.webp"},
        {name: "Oddly-shaped Opal", sotv: true, sots: false, image: "images/itemsWhite/Oddly-shaped_Opal.webp"},
        {name: "Paul's Goat Hoof", sotv: false, sots: false, image: "images/itemsWhite/Paul's_Goat_Hoof.webp"},
        {name: "Personal Shield Generator", sotv: false, sots: false, image: "images/itemsWhite/Personal_Shield_Generator.webp"},
        {name: "Power Elixir", sotv: true, sots: false, image: "images/itemsWhite/Power_Elixir.webp"},
        {name: "Repulsion Armor Plate", sotv: false, sots: false, image: "images/itemsWhite/Repulsion_Armor_Plate.webp"},
        {name: "Roll of Pennies", sotv: true, sots: false, image: "images/itemsWhite/Roll_of_Pennies.webp"},
        {name: "Rusted Key", sotv: false, sots: false, image: "images/itemsWhite/Rusted_Key.webp"},
        {name: "Soldier's Syringe", sotv: false, sots: false, image: "images/itemsWhite/Soldier's_Syringe.webp"},
        {name: "Sticky Bomb", sotv: false, sots: false, image: "images/itemsWhite/Sticky_Bomb.webp"},
        {name: "Stun Grenade", sotv: false, sots: false, image: "images/itemsWhite/Stun_Grenade.webp"},
        {name: "Topaz Brooch", sotv: false, sots: false, image: "images/itemsWhite/Topaz_Brooch.webp"},
        {name: "Tougher Times", sotv: false, sots: false, image: "images/itemsWhite/Tougher_Times.webp"},
        {name: "Tri-Tip Dagger", sotv: false, sots: false, image: "images/itemsWhite/Tri-Tip_Dagger.webp"},
        {name: "Warbanner", sotv: false, sots: false, image: "images/itemsWhite/Warbanner.webp"},
        {name: "Warped Echo", sotv: false, sots: true, image: "images/itemsWhite/Warped_Echo.webp"}
    ],
    green: [
        {name: "AtG Missile Mk. 1", sotv: false, sots: false, image: "images/itemsGreen/AtG_Missile_Mk._1.webp"},
        {name: "Bandolier", sotv: false, sots: false, image: "images/itemsGreen/Bandolier.webp"},
        {name: "Berzerker's Pauldron", sotv: false, sots: false, image: "images/itemsGreen/Berzerker's_Pauldron.webp"},
        {name: "Breaching Fin", sotv: false, sots: true, image: "images/itemsGreen/Breaching_Fin.webp"},
        {name: "Chance Doll", sotv: false, sots: true, image: "images/itemsGreen/Chance_Doll.webp"},
        {name: "Chronobauble", sotv: false, sots: false, image: "images/itemsGreen/Chronobauble.webp"},
        {name: "Death Mark", sotv: false, sots: false, image: "images/itemsGreen/Death_Mark.webp"},
        {name: "Fuel Cell", sotv: false, sots: false, image: "images/itemsGreen/Fuel_Cell.webp"},
        {name: "Ghor's Tome", sotv: false, sots: false, image: "images/itemsGreen/Ghor's_Tome.webp"},
        {name: "Harvester's Scythe", sotv: false, sots: false, image: "images/itemsGreen/Harvester's_Scythe.webp"},
        {name: "Hopoo Feather", sotv: false, sots: false, image: "images/itemsGreen/Hopoo_Feather.webp"},
        {name: "Hunter's Harpoon", sotv: true, sots: false, image: "images/itemsGreen/Hunter's_Harpoon.webp"},
        {name: "Ignition Tank", sotv: true, sots: false, image: "images/itemsGreen/Ignition_Tank.webp"},
        {name: "Infusion", sotv: false, sots: false, image: "images/itemsGreen/Infusion.webp"},
        {name: "Item Scrap, Green", sotv: false, sots: false, image: "images/itemsGreen/Item_Scrap,_Green.webp"},
        {name: "Kjaro's Band", sotv: false, sots: false, image: "images/itemsGreen/Kjaro's_Band.webp"},
        {name: "Leeching Seed", sotv: false, sots: false, image: "images/itemsGreen/Leeching_Seed.webp"},
        {name: "Lepton Daisy", sotv: false, sots: false, image: "images/itemsGreen/Lepton_Daisy.webp"},
        {name: "Luminous Shot", sotv: false, sots: true, image: "images/itemsGreen/Luminous_Shot.webp"},
        {name: "Noxious Thorn", sotv: false, sots: true, image: "images/itemsGreen/Noxious_Thorn.webp"},
        {name: "Old Guillotine", sotv: false, sots: false, image: "images/itemsGreen/Old_Guillotine.webp"},
        {name: "Old War Stealthkit", sotv: false, sots: false, image: "images/itemsGreen/Old_War_Stealthkit.webp"},
        {name: "Prayer Beads", sotv: false, sots: true, image: "images/itemsGreen/Prayer_Beads.webp"},
        {name: "Predatory Instincts", sotv: false, sots: false, image: "images/itemsGreen/Predatory_Instincts.webp"},
        {name: "Razorwire", sotv: false, sots: false, image: "images/itemsGreen/Razorwire.webp"},
        {name: "Red Whip", sotv: false, sots: false, image: "images/itemsGreen/Red_Whip.webp"},
        {name: "Regenerating Scrap", sotv: true, sots: false, image: "images/itemsGreen/Regenerating_Scrap.webp"},
        {name: "Rose Buckler", sotv: false, sots: false, image: "images/itemsGreen/Rose_Buckler.webp"},
        {name: "Runald's Band", sotv: false, sots: false, image: "images/itemsGreen/Runald's_Band.webp"},
        {name: "Sale Star", sotv: false, sots: true, image: "images/itemsGreen/Sale_Star.webp"},
        {name: "Shipping Request Form", sotv: true, sots: false, image: "images/itemsGreen/Shipping_Request_Form.webp"},
        {name: "Shuriken", sotv: true, sots: false, image: "images/itemsGreen/Shuriken.webp"},
        {name: "Squid Polyp", sotv: false, sots: false, image: "images/itemsGreen/Squid_Polyp.webp"},
        {name: "Ukulele", sotv: false, sots: false, image: "images/itemsGreen/Ukulele.webp"},
        {name: "Unstable Transmitter", sotv: false, sots: true, image: "images/itemsGreen/Unstable_Transmitter.webp"},
        {name: "War Horn", sotv: false, sots: false, image: "images/itemsGreen/War_Horn.webp"},
        {name: "Wax Quail", sotv: false, sots: false, image: "images/itemsGreen/Wax_Quail.webp"},
        {name: "Will-o'-the-wisp", sotv: false, sots: false, image: "images/itemsGreen/Will-o'-the-wisp.webp"}
    ],
    red: [
        {name: "57 Leaf Clover", sotv: false, sots: false, image: "images/itemsRed/57_Leaf_Clover.webp"},
        {name: "Aegis", sotv: false, sots: false, image: "images/itemsRed/Aegis.webp"},
        {name: "Alien Head", sotv: false, sots: false, image: "images/itemsRed/Alien_Head.webp"},
        {name: "Ben's Raincoat", sotv: true, sots: false, image: "images/itemsRed/Ben's_Raincoat.webp"},
        {name: "Bottled Chaos", sotv: true, sots: false, image: "images/itemsRed/Bottled_Chaos.webp"},
        {name: "Brainstalks", sotv: false, sots: false, image: "images/itemsRed/Brainstalks.webp"},
        {name: "Brilliant Behemoth", sotv: false, sots: false, image: "images/itemsRed/Brilliant_Behemoth.webp"},
        {name: "Ceremonial Dagger", sotv: false, sots: false, image: "images/itemsRed/Ceremonial_Dagger.webp"},
        {name: "Defensive Microbots", sotv: false, sots: false, image: "images/itemsRed/Defensive_Microbots.webp"},
        {name: "Dio's Best Friend", sotv: false, sots: false, image: "images/itemsRed/Dio's_Best_Friend.webp"},
        {name: "Electric Boomerang", sotv: false, sots: true, image: "images/itemsRed/Electric_Boomerang.webp"},
        {name: "Frost Relic", sotv: false, sots: false, image: "images/itemsRed/Frost_Relic.webp"},
        {name: "Growth Nectar", sotv: false, sots: true, image: "images/itemsRed/Growth_Nectar.webp"},
        {name: "H3AD-5T v2", sotv: false, sots: false, image: "images/itemsRed/H3AD-5T_v2.webp"},
        {name: "Happiest Mask", sotv: false, sots: false, image: "images/itemsRed/Happiest_Mask.webp"},
        {name: "Hardlight Afterburner", sotv: false, sots: false, image: "images/itemsRed/Hardlight_Afterburner.webp"},
        {name: "Interstellar Desk Plant", sotv: false, sots: false, image: "images/itemsRed/Interstellar_Desk_Plant.webp"},
        {name: "Item Scrap, Red", sotv: false, sots: false, image: "images/itemsRed/Item_Scrap,_Red.webp"},
        {name: "Laser Scope", sotv: true, sots: false, image: "images/itemsRed/Laser_Scope.webp"},
        {name: "N'kuhana's Opinion", sotv: false, sots: false, image: "images/itemsRed/N'kuhana's_Opinion.webp"},
        {name: "Pocket I.C.B.M.", sotv: true, sots: false, image: "images/itemsRed/Pocket_I.C.B.M..webp"},
        {name: "Rejuvenation Rack", sotv: false, sots: false, image: "images/itemsRed/Rejuvenation_Rack.webp"},
        {name: "Resonance Disc", sotv: false, sots: false, image: "images/itemsRed/Resonance_Disc.webp"},
        {name: "Runic Lens", sotv: false, sots: true, image: "images/itemsRed/Runic_Lens.webp"},
        {name: "Sentient Meat Hook", sotv: false, sots: false, image: "images/itemsRed/Sentient_Meat_Hook.webp"},
        {name: "Shattering Justice", sotv: false, sots: false, image: "images/itemsRed/Shattering_Justice.webp"},
        {name: "Sonorous Whispers", sotv: false, sots: true, image: "images/itemsRed/Sonorous_Whispers.webp"},
        {name: "Soulbound Catalyst", sotv: false, sots: false, image: "images/itemsRed/Soulbound_Catalyst.webp"},
        {name: "Spare Drone Parts", sotv: true, sots: false, image: "images/itemsRed/Spare_Drone_Parts.webp"},
        {name: "Symbiotic Scorpion", sotv: true, sots: false, image: "images/itemsRed/Symbiotic_Scorpion.webp"},
        {name: "Unstable Tesla Coil", sotv: false, sots: false, image: "images/itemsRed/Unstable_Tesla_Coil.webp"},
        {name: "Wake of Vultures", sotv: false, sots: false, image: "images/itemsRed/Wake_of_Vultures.webp"},
        {name: "War Bonds", sotv: false, sots: true, image: "images/itemsRed/War_Bonds.webp"}
    ],
    yellow: [
        {name: "Charged Perforator", sotv: false, sots: false, image: "images/itemsYellow/Charged_Perforator.webp"},
        {name: "Defense Nucleus", sotv: true, sots: false, image: "images/itemsYellow/Defense_Nucleus.webp"},
        {name: "Empathy Cores", sotv: false, sots: false, image: "images/itemsYellow/Empathy_Cores.webp"},
        {name: "Genesis Loop", sotv: false, sots: false, image: "images/itemsYellow/Genesis_Loop.webp"},
        {name: "Halcyon Seed", sotv: false, sots: false, image: "images/itemsYellow/Halcyon_Seed.webp"},
        {name: "Irradiant Pearl", sotv: false, sots: false, image: "images/itemsYellow/Irradiant_Pearl.webp"},
        {name: "Item Scrap, Yellow", sotv: false, sots: false, image: "images/itemsYellow/Item_Scrap,_Yellow.webp"},
        {name: "Little Disciple", sotv: false, sots: false, image: "images/itemsYellow/Little_Disciple.webp"},
        {name: "Mired Urn", sotv: false, sots: false, image: "images/itemsYellow/Mired_Urn.webp"},
        {name: "Molten Perforator", sotv: false, sots: false, image: "images/itemsYellow/Molten_Perforator.webp"},
        {name: "Pearl", sotv: false, sots: false, image: "images/itemsYellow/Pearl.webp"},
        {name: "Planula", sotv: false, sots: false, image: "images/itemsYellow/Planula.webp"},
        {name: "Queen's Gland", sotv: false, sots: false, image: "images/itemsYellow/Queen's_Gland.webp"},
        {name: "Shatterspleen", sotv: false, sots: false, image: "images/itemsYellow/Shatterspleen.webp"},
        {name: "Titanic Knurl", sotv: false, sots: false, image: "images/itemsYellow/Titanic_Knurl.webp"}
    ],
    lunar: [
        {name: "Brittle Crown", sotv: false, sots: false, image: "images/itemsLunar/Brittle_Crown.webp"},
        {name: "Corpsebloom", sotv: false, sots: false, image: "images/itemsLunar/Corpsebloom.webp"},
        {name: "Defiant Gouge", sotv: false, sots: false, image: "images/itemsLunar/Defiant_Gouge.webp"},
        {name: "Egocentrism", sotv: true, sots: false, image: "images/itemsLunar/Egocentrism.webp"},
        {name: "Essence of Heresy", sotv: false, sots: false, image: "images/itemsLunar/Essence_of_Heresy.webp"},
        {name: "Eulogy Zero", sotv: true, sots: false, image: "images/itemsLunar/Eulogy_Zero.webp"},
        {name: "Focused Convergence", sotv: false, sots: false, image: "images/itemsLunar/Focused_Convergence.webp"},
        {name: "Gesture of the Drowned", sotv: false, sots: false, image: "images/itemsLunar/Gesture_of_the_Drowned.webp"},
        {name: "Hooks of Heresy", sotv: false, sots: false, image: "images/itemsLunar/Hooks_of_Heresy.webp"},
        {name: "Light Flux Pauldron", sotv: true, sots: false, image: "images/itemsLunar/Light_Flux_Pauldron.webp"},
        {name: "Mercurial Rachis", sotv: false, sots: false, image: "images/itemsLunar/Mercurial_Rachis.webp"},
        {name: "Purity", sotv: false, sots: false, image: "images/itemsLunar/Purity.webp"},
        {name: "Shaped Glass", sotv: false, sots: false, image: "images/itemsLunar/Shaped_Glass.webp"},
        {name: "Strides of Heresy", sotv: false, sots: false, image: "images/itemsLunar/Strides_of_Heresy.webp"},
        {name: "Transcendence", sotv: false, sots: false, image: "images/itemsLunar/Transcendence.webp"},
        {name: "Visions of Heresy", sotv: false, sots: false, image: "images/itemsLunar/Visions_of_Heresy.webp"}
    ],
    voidWhite: [
        {name: "Encrusted Key", sotv: true, sots: false, image: "images/itemsVoid/Encrusted_Key.webp"},
        {name: "Lost Seer's Lenses", sotv: true, sots: false, image: "images/itemsVoid/Lost_Seer's_Lenses.webp"},
        {name: "Needletick", sotv: true, sots: false, image: "images/itemsVoid/Needletick.webp"},
        {name: "Safer Spaces", sotv: true, sots: false, image: "images/itemsVoid/Safer_Spaces.webp"},
        {name: "Weeping Fungus", sotv: true, sots: false, image: "images/itemsVoid/Weeping_Fungus.webp"}
    ],
    voidGreen: [
        {name: "Voidsent Flame", sotv: true, sots: false, image: "images/itemsVoid/Voidsent_Flame.webp"},
        {name: "Singularity Band", sotv: true, sots: false, image: "images/itemsVoid/Singularity_Band.webp"},
        {name: "Polylute", sotv: true, sots: false, image: "images/itemsVoid/Polylute.webp"},
        {name: "Plasma Shrimp", sotv: true, sots: false, image: "images/itemsVoid/Plasma_Shrimp.webp"},
        {name: "Tentabauble", sotv: true, sots: false, image: "images/itemsVoid/Tentabauble.webp"},
        {name: "Lysate Cell", sotv: true, sots: false, image: "images/itemsVoid/Lysate_Cell.webp"}
    ],
    voidRed: [
        {name: "Pluripotent Larva", sotv: true, sots: false, image: "images/itemsVoid/Pluripotent_Larva.webp"},
        {name: "Benthic Bloom", sotv: true, sots: false, image: "images/itemsVoid/Benthic_Bloom.webp"}
    ],
    voidYellow: [
        {name: "Newly Hatched Zoea", sotv: true, sots: false, image: "images/itemsVoid/Newly_Hatched_Zoea.webp"}
    ],
    equipment: [
        {name: "Blast Shower", sotv: false, sots: false, image: "images/itemsEquipment/Blast_Shower.webp"},
        {name: "Disposable Missile Launcher", sotv: false, sots: false, image: "images/itemsEquipment/Disposable_Missile_Launcher.webp"},
        {name: "Eccentric Vase", sotv: false, sots: false, image: "images/itemsEquipment/Eccentric_Vase.webp"},
        {name: "Executive Card", sotv: true, sots: false, image: "images/itemsEquipment/Executive_Card.webp"},
        {name: "Foreign Fruit", sotv: false, sots: false, image: "images/itemsEquipment/Foreign_Fruit.webp"},
        {name: "Forgive Me Please", sotv: false, sots: false, image: "images/itemsEquipment/Forgive_Me_Please.webp"},
        {name: "Fuel Array", sotv: false, sots: false, image: "images/itemsEquipment/Fuel_Array.webp"},
        {name: "Gnarled Woodsprite", sotv: false, sots: false, image: "images/itemsEquipment/Gnarled_Woodsprite.webp"},
        {name: "Goobo Jr.", sotv: true, sots: false, image: "images/itemsEquipment/Goobo_Jr..webp"},
        {name: "Gorag's Opus", sotv: false, sots: false, image: "images/itemsEquipment/Gorag's_Opus.webp"},
        {name: "Jade Elephant", sotv: false, sots: false, image: "images/itemsEquipment/Jade_Elephant.webp"},
        {name: "Milky Chrysalis", sotv: false, sots: false, image: "images/itemsEquipment/Milky_Chrysalis.webp"},
        {name: "Molotov (6-Pack)", sotv: true, sots: false, image: "images/itemsEquipment/Molotov_(6-Pack).webp"},
        {name: "Ocular HUD", sotv: false, sots: false, image: "images/itemsEquipment/Ocular_HUD.webp"},
        {name: "Preon Accumulator", sotv: false, sots: false, image: "images/itemsEquipment/Preon_Accumulator.webp"},
        {name: "Primordial Cube", sotv: false, sots: false, image: "images/itemsEquipment/Primordial_Cube.webp"},
        {name: "Radar Scanner", sotv: false, sots: false, image: "images/itemsEquipment/Radar_Scanner.webp"},
        {name: "Recycler", sotv: false, sots: false, image: "images/itemsEquipment/Recycler.webp"},
        {name: "Remote Caffeinator", sotv: true, sots: false, image: "images/itemsEquipment/Remote_Caffeinator.webp"},
        {name: "Royal Capacitor", sotv: false, sots: false, image: "images/itemsEquipment/Royal_Capacitor.webp"},
        {name: "Sawmerang", sotv: false, sots: false, image: "images/itemsEquipment/Sawmerang.webp"},
        {name: "Seed of Life", sotv: false, sots: true, image: "images/itemsEquipment/Seed_of_Life.webp"},
        {name: "Seed of Life (Consumed)", sotv: false, sots: true, image: "images/itemsEquipment/Seed_of_Life_(Consumed).webp"},
        {name: "Super Massive Leech", sotv: false, sots: false, image: "images/itemsEquipment/Super_Massive_Leech.webp"},
        {name: "The Back-up", sotv: false, sots: false, image: "images/itemsEquipment/The_Back-up.webp"},
        {name: "The Crowdfunder", sotv: false, sots: false, image: "images/itemsEquipment/The_Crowdfunder.webp"},
        {name: "Trophy Hunter's Tricorn", sotv: true, sots: false, image: "images/itemsEquipment/Trophy_Hunter's_Tricorn.webp"},
        {name: "Trophy Hunter's Tricorn (Consumed)", sotv: true, sots: false, image: "images/itemsEquipment/Trophy_Hunter's_Tricorn_(Consumed).webp"},
        {name: "Volcanic Egg", sotv: false, sots: false, image: "images/itemsEquipment/Volcanic_Egg.webp"}
    ],
    equipmentLunar: [
        {name: "Effigy of Grief", sotv: false, sots: false, image: "images/itemsEquipmentLunar/Effigy_of_Grief.webp"},
        {name: "Glowing Meteorite", sotv: false, sots: false, image: "images/itemsEquipmentLunar/Glowing_Meteorite.webp"},
        {name: "Helfire Tincture", sotv: false, sots: false, image: "images/itemsEquipmentLunar/Helfire_Tincture.webp"},
        {name: "Spinel Tonic", sotv: false, sots: false, image: "images/itemsEquipmentLunar/Spinel_Tonic.webp"}
    ],
    equipmentElite: [
        {name: "Aurelionite's Blessing", sotv: false, sots: true, image: "images/itemsEquipmentElite/Aurelionite's_Blessing.webp"},
        {name: "Her Biting Embrace", sotv: false, sots: false, image: "images/itemsEquipmentElite/Her_Biting_Embrace.webp"},
        {name: "His Reassurance", sotv: true, sots: false, image: "images/itemsEquipmentElite/His_Reassurance.webp"},
        {name: "His Spiteful Boon", sotv: false, sots: true, image: "images/itemsEquipmentElite/His_Spiteful_Boon.webp"},
        {name: "Ifrit's Distinction", sotv: false, sots: false, image: "images/itemsEquipmentElite/Ifrit's_Distinction.webp"},
        {name: "N'kuhana's Retort", sotv: false, sots: false, image: "images/itemsEquipmentElite/N'kuhana's_Retort.webp"},
        {name: "Shared Design", sotv: false, sots: false, image: "images/itemsEquipmentElite/Shared_Design.webp"},
        {name: "Silence Between Two Strikes", sotv: false, sots: false, image: "images/itemsEquipmentElite/Silence_Between_Two_Strikes.webp"},
        {name: "Spectral Circlet", sotv: false, sots: false, image: "images/itemsEquipmentElite/Spectral_Circlet.webp"}
    ],
    artifacts: [
        {name: "Chaos", description: "Friendly fire is enabled for both survivors and monsters alike.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Chaos.webp"},
        {name: "Command", description: "Choose your items.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Command.webp"},
        {name: "Death", description: "When one player dies, everyone dies. Enable only if you want to truly put your teamwork and individual skill to the ultimate test.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Death.webp"},
        {name: "Delusion", description: "Risk your items after completing the teleporter event in a test of memory to gain more items.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Delusion.webp"},
        {name: "Devotion", description: "Replace broken drones with Lemurian Eggs. Offer an item to gain followers.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Devotion.webp"},
        {name: "Dissonance", description: "Monsters can appear outside their usual environments.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Dissonance.webp"},
        {name: "Enigma", description: "Spawn with a random equipment that changes every time it's activated.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Enigma.webp"},
        {name: "Evolution", description: "Monsters gain items between stages.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Evolution.webp"},
        {name: "Frailty", description: "Fall damage is doubled and lethal.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Frailty.webp"},
        {name: "Glass", description: "Allies deal 500% damage, but have 10% health.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Glass.webp"},
        {name: "Honor", description: "Enemies can only spawn as elites.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Honor.webp"},
        {name: "Kin", description: "Monsters will be of only one type per stage.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Kin.webp"},
        {name: "Metamorphosis", description: "Players always spawn as a random survivor.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Metamorphosis.webp"},
        {name: "Rebirth", description: "Descend to Petrichor V with gifts from a previous life.", sotv: false, sots: true, image: "images/artifacts/Artifact_of_Rebirth.png"},
        {name: "Sacrifice", description: "Monsters drop items on death, but Chests no longer spawn.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Sacrifice.webp"},
        {name: "Soul", description: "Wisps emerge from defeated monsters.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Soul.webp"},
        {name: "Spite", description: "Enemies drop multiple exploding bombs on death.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Spite.webp"},
        {name: "Swarms", description: "Monster spawns are doubled, but monster maximum health is halved.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Swarms.webp"},
        {name: "Vengeance", description: "Your relentless doppelganger will invade every 10 minutes.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Vengeance.webp"}
    ]
};