const items = {
    survivors: [
        {name: "Acrid", description: "Acrid is a melee-range hybrid who uses powerful poisons to melt tanky enemies. ",sotv: false, sots: false, image: "images/survivors/Acrid.webp"},
        {name: "Artificer", description: "The Artificer is a high burst damage survivor who excels in fighting large groups and bosses alike. ",sotv: false, sots: false, image: "images/survivors/Artificer.webp"},
        {name: "Bandit", description: "The Bandit is a high-skill combo character that can dish out devastating backstabs while weaving in and out of stealth. ",sotv: false, sots: false, image: "images/survivors/Bandit.webp"},
        {name: "Captain", description: "The Captain is a unique survivor that can control the battlefield with utility and damage - with help from the UES Safe Travels. ",sotv: false, sots: false, image: "images/survivors/Captain.webp"},
        {name: "Chef", description: "A survivor of high class, CHEF specializes in only the most exquisite meals and combos. As a culinary master, CHEF uses a variety of practiced skills in tandem for additional benefits.",sotv: false, sots: true, image: "images/survivors/CHEF.webp"},
        {name: "Commando", description: "The Commando is a jack-of-all-trades character that is reliable in all situations of the game. ",sotv: false, sots: false, image: "images/survivors/Commando.webp"},
        {name: "Engineer", description: "The Engineer is a unique class that requires planning and positioning to be successful.",sotv: false, sots: false, image: "images/survivors/Engineer.webp"},
        {name: "False Son", description: "The False Son is a slow but stalwart close-range warrior. With extreme health and defense, False Son can weather any storm. Use False Son's durability to stay in the fray and capitalize on his slow but deadly skills. ",sotv: false, sots: true, image: "images/survivors/False_Son.webp"},
        {name: "Heretic", description: "The Heretic is a powerful character who can only be accessed through extraordinary means. ",sotv: false, sots: false, image: "images/survivors/Heretic.webp"},
        {name: "Huntress", description: "The Huntress is an extremely mobile but fragile survivor with a high damage output. ",sotv: false, sots: false, image: "images/survivors/Huntress.webp"},
        {name: "Loader", description: "The Loader is a slow but powerful bruiser that can use her grappling hook to uniquely navigate the environment. ",sotv: false, sots: false, image: "images/survivors/Loader.webp"},
        {name: "Mercenary", description: "The Mercenary is a high skill melee survivor that uses his many dodges to weave in and out of combat. ",sotv: false, sots: false, image: "images/survivors/Mercenary.webp"},
        {name: "MUL-T", description: "MUL-T is an aggressive survivor who has the tools necessary for any job! ",sotv: false, sots: false, image: "images/survivors/MUL-T.webp"},
        {name: "Railgunner", description: "The Railgunner is a long-range, single target survivor that can instantly kill any high priority target - and from any range. ",sotv: true, sots: false, image: "images/survivors/Railgunner.webp"},
        {name: "Seeker", description: "As a meditative mid-range brawler, Seeker utilizes powerful healing to sustain herself and her team. ",sotv: false, sots: true, image: "images/survivors/Seeker.webp"},
        {name: "REX", description: "REX is a half robot / half plant that uses HP to cast devastating skills from a distance. The plant nor the robot could survive this planet alone – but thankfully they have each other. ",sotv: false, sots: false, image: "images/survivors/REX.webp"},
        {name: "Void Fiend", description: "The Void Fiend is a corrupted survivor that fluctuates between a controlled and corrupted form, each with different strengths and weaknesses. Managing this curse has become its fate. ",sotv: true, sots: false, image: "images/survivors/Void_Fiend.webp"}
    ],
    white: [
        {name: "Armor-Piercing Rounds", description: "Deal an additional [yellow:20%] damage [gray:(+20% per stack)] to bosses.", sotv: false, sots: false, image: "images/itemsWhite/Armor-Piercing_Rounds.webp"},
        {name: "Backup Magazine", description: "Add [blue:+1] [gray:(+1 per stack)] charge of your [blue:Secondary skill].", sotv: false, sots: false, image: "images/itemsWhite/Backup_Magazine.webp"},
        {name: "Bison Steak", description: "Increases [green:maximum health] by [green:25] [gray:(+25 per stack)].",sotv: false, sots: false, image: "images/itemsWhite/Bison_Steak.webp"},
        {name: "Bolstering Lantern", description: "Increase your [yellow:attack speed] by [yellow:10%] [gray:(+3.5% per stack)] for up to [blue:3] [gray:(+1 per stack)] enemies and allies within [blue:20] meters.",sotv: false, sots: true, image: "images/itemsWhite/Bolstering_Lantern.webp"},
        {name: "Bundle of Fireworks", description: "Activating an interactable [yellow:launches 8] [gray:(+4 per stack)] [yellow:fireworks] that deal [yellow:300%] base damage.",sotv: false, sots: false, image: "images/itemsWhite/Bundle_of_Fireworks.webp"},
        {name: "Bustling Fungus", description: "After standing still for [green:1] second, create a zone that [green:heals] for [green:4.5%] (+2.25% per stack) of your [green:health] every second to all allies within [green:3m] (+1.5m per stack). ",sotv: false, sots: false, image: "images/itemsWhite/Bustling_Fungus.webp"},
        {name: "Cautious Slug", description: "Increases [green:base health regeneration] by [green:+3 hp/s] (+3 hp/s per stack) while outside of combat. ",sotv: false, sots: false, image: "images/itemsWhite/Cautious_Slug.webp"},
        {name: "Chronic Expansion", description: "Killing an enemy increase your damage by [yellow:3.5] (+1% per stack), up to [blue:10] (+5 per stack), for [blue:7s]. Dealing damage refreshes the timer. ",sotv: false, sots: true, image: "images/itemsWhite/Chronic_Expansion.webp"},
        {name: "Crowbar", description: "Deal [yellow:+75%] (+75% per stack) damage to enemies above [yellow:90% health].",sotv: false, sots: false, image: "images/itemsWhite/Crowbar.webp"},
        {name: "Delicate Watch", description: "Increase damage by [yellow:20%] (+20% per stack). Taking damage to below [red:25% health] [blue:breaks] this item.",sotv: true, sots: false, image: "images/itemsWhite/Delicate_Watch.webp"},
        {name: "Elusive Antlers", description: "Spawns orbs of energy nearby every [blue:10s] (-10% per stack), giving [blue:+12% movement speed] up to [blue:3] (+3 per stack) [blue:times] for [blue:12s].",sotv: false, sots: true, image: "images/itemsWhite/Elusive_Antlers.webp"},
        {name: "Energy Drink", description: "[blue:Sprint speed] is improved by [blue:25%] (+25% per stack).",sotv: false, sots: false, image: "images/itemsWhite/Energy_Drink.webp"},
        {name: "Focus Crystal", description: "Increase damage to enemies within [yellow:13m] by [yellow:20%] (+20% per stack).",sotv: false, sots: false, image: "images/itemsWhite/Focus_Crystal.webp"},
        {name: "Gasoline", description: "Killing an enemy [yellow:ignites] all enemies within [yellow:12m] (+4m per stack) for [yellow:150%] base damage. Additionally, enemies [yellow:burn] for [yellow:150%] (+75% per stack) base damage. ",sotv: false, sots: false, image: "images/itemsWhite/Gasoline.webp"},
        {name: "Item Scrap, White", description: "Does nothing. Prioritized when used with 3D Printers.",sotv: false, sots: false, image: "images/itemsWhite/Item_Scrap,_White.webp"},
        {name: "Lens-Maker's Glasses", description: "Your attacks have a [yellow:10%] (+10% per stack) chance to '[yellow:Critically Strike]', dealing [yellow:double damage]. ",sotv: false, sots: false, image: "images/itemsWhite/Lens-Maker's_Glasses.webp"},
        {name: "Medkit", description: "",sotv: false, sots: false, image: "images/itemsWhite/Medkit.webp"},
        {name: "Mocha", description: "",sotv: true, sots: false, image: "images/itemsWhite/Mocha.webp"},
        {name: "Monster Tooth", description: "",sotv: false, sots: false, image: "images/itemsWhite/Monster_Tooth.webp"},
        {name: "Oddly-shaped Opal", description: "",sotv: true, sots: false, image: "images/itemsWhite/Oddly-shaped_Opal.webp"},
        {name: "Paul's Goat Hoof", description: "",sotv: false, sots: false, image: "images/itemsWhite/Paul's_Goat_Hoof.webp"},
        {name: "Personal Shield Generator", description: "",sotv: false, sots: false, image: "images/itemsWhite/Personal_Shield_Generator.webp"},
        {name: "Power Elixir", description: "",sotv: true, sots: false, image: "images/itemsWhite/Power_Elixir.webp"},
        {name: "Repulsion Armor Plate", description: "",sotv: false, sots: false, image: "images/itemsWhite/Repulsion_Armor_Plate.webp"},
        {name: "Roll of Pennies", description: "",sotv: true, sots: false, image: "images/itemsWhite/Roll_of_Pennies.webp"},
        {name: "Rusted Key", description: "",sotv: false, sots: false, image: "images/itemsWhite/Rusted_Key.webp"},
        {name: "Soldier's Syringe", description: "",sotv: false, sots: false, image: "images/itemsWhite/Soldier's_Syringe.webp"},
        {name: "Sticky Bomb", description: "",sotv: false, sots: false, image: "images/itemsWhite/Sticky_Bomb.webp"},
        {name: "Stun Grenade", description: "",sotv: false, sots: false, image: "images/itemsWhite/Stun_Grenade.webp"},
        {name: "Topaz Brooch", description: "",sotv: false, sots: false, image: "images/itemsWhite/Topaz_Brooch.webp"},
        {name: "Tougher Times", description: "",sotv: false, sots: false, image: "images/itemsWhite/Tougher_Times.webp"},
        {name: "Tri-Tip Dagger", description: "",sotv: false, sots: false, image: "images/itemsWhite/Tri-Tip_Dagger.webp"},
        {name: "Warbanner", description: "",sotv: false, sots: false, image: "images/itemsWhite/Warbanner.webp"},
        {name: "Warped Echo", description: "",sotv: false, sots: true, image: "images/itemsWhite/Warped_Echo.webp"}
    ],
    green: [
        {name: "AtG Missile Mk. 1", description: "Chance to fire a missile.", sotv: false, sots: false, image: "images/itemsGreen/AtG_Missile_Mk._1.webp"},
        {name: "Bandolier", description: "Chance on kill to drop an ammo pack that resets all skill cooldowns.", sotv: false, sots: false, image: "images/itemsGreen/Bandolier.webp"},
        {name: "Berzerker's Pauldron", description: "Enter a frenzy after killing 4 enemies in quick succession.", sotv: false, sots: false, image: "images/itemsGreen/Berzerker's_Pauldron.webp"},
        {name: "Breaching Fin", description: "Grounded enemies hit with any skill are launched and take bonus damage. ", sotv: false, sots: true, image: "images/itemsGreen/Breaching_Fin.webp"},
        {name: "Chance Doll", description: "Gain 40% chance to increase item rarity at Shrines of Chance. ", sotv: false, sots: true, image: "images/itemsGreen/Chance_Doll.webp"},
        {name: "Chronobauble", description: "Slow enemies on hit. ", sotv: false, sots: false, image: "images/itemsGreen/Chronobauble.webp"},
        {name: "Death Mark", description: "Enemies with 4 or more debuffs are marked for death, taking bonus damage. ", sotv: false, sots: false, image: "images/itemsGreen/Death_Mark.webp"},
        {name: "Fuel Cell", description: "Hold an additional equipment charge. Reduce equipment cooldown. ", sotv: false, sots: false, image: "images/itemsGreen/Fuel_Cell.webp"},
        {name: "Ghor's Tome", description: "Chance on kill to drop a treasure. ", sotv: false, sots: false, image: "images/itemsGreen/Ghor's_Tome.webp"},
        {name: "Harvester's Scythe", description: "'Critical Strikes' heal you. ", sotv: false, sots: false, image: "images/itemsGreen/Harvester's_Scythe.webp"},
        {name: "Hopoo Feather", description: "Gain an extra jump. ", sotv: false, sots: false, image: "images/itemsGreen/Hopoo_Feather.webp"},
        {name: "Hunter's Harpoon", description: "Killing an enemy gives you a burst of movement speed. ", sotv: true, sots: false, image: "images/itemsGreen/Hunter's_Harpoon.webp"},
        {name: "Ignition Tank", description: "Your ignite effects deal quadruple damage. ", sotv: true, sots: false, image: "images/itemsGreen/Ignition_Tank.webp"},
        {name: "Infusion", description: "Killing an enemy permanently increases your maximum health, up to 100. ", sotv: false, sots: false, image: "images/itemsGreen/Infusion.webp"},
        {name: "Item Scrap, Green", description: "Does nothing. Prioritized when used with 3D Printers. ", sotv: false, sots: false, image: "images/itemsGreen/Item_Scrap,_Green.webp"},
        {name: "Kjaro's Band", description: "High damage hits also blasts enemies with a runic flame tornado. Recharges over time. ", sotv: false, sots: false, image: "images/itemsGreen/Kjaro's_Band.webp"},
        {name: "Leeching Seed", description: "Dealing damage heals you. ", sotv: false, sots: false, image: "images/itemsGreen/Leeching_Seed.webp"},
        {name: "Lepton Daisy", description: "Periodically release a healing nova during the Teleporter event and 'Holdout Zones' such as the Void Fields. ", sotv: false, sots: false, image: "images/itemsGreen/Lepton_Daisy.webp"},
        {name: "Luminous Shot", description: "Activating your Secondary skill charges your Primary skill with powerful lightning strikes. Requires 3 charges. ", sotv: false, sots: true, image: "images/itemsGreen/Luminous_Shot.webp"},
        {name: "Noxious Thorn", description: "Killing an enemy transfers debuffs to a nearby enemy. ", sotv: false, sots: true, image: "images/itemsGreen/Noxious_Thorn.webp"},
        {name: "Old Guillotine", description: "Instantly kill low health Elite monsters. ", sotv: false, sots: false, image: "images/itemsGreen/Old_Guillotine.webp"},
        {name: "Old War Stealthkit", sotv: false, sots: false, image: "images/itemsGreen/Old_War_Stealthkit.webp"},
        {name: "Prayer Beads", sotv: false, sots: true, image: "images/itemsGreen/Prayer_Beads.webp"},
        {name: "Predatory Instincts", sotv: false, sots: false, image: "images/itemsGreen/Predatory_Instincts.webp"},
        {name: "Razorwire", sotv: false, sots: false, image: "images/itemsGreen/Razorwire.webp"},
        {name: "Red Whip", sotv: false, sots: false, image: "images/itemsGreen/Red_Whip.webp"},
        {name: "Regenerating Scrap", sotv: true, sots: false, image: "images/itemsGreen/Regenerating_Scrap.webp"},
        {name: "Rose Buckler", sotv: false, sots: false, image: "images/itemsGreen/Rose_Buckler.webp"},
        {name: "Runald's Band", sotv: false, sots: false, image: "images/itemsGreen/Runald's_Band.webp"},
        {name: "Sale Star", sotv: false, sots: true, image: "images/itemsGreen/Sale_Star.webp"},
        {name: "Shipping Request Form", sotv: true, sots: false, image: "images/itemsGreen/Shipping_Request_Form.webp"},
        {name: "Shuriken", sotv: true, sots: false, image: "images/itemsGreen/Shuriken.webp"},
        {name: "Squid Polyp", sotv: false, sots: false, image: "images/itemsGreen/Squid_Polyp.webp"},
        {name: "Ukulele", sotv: false, sots: false, image: "images/itemsGreen/Ukulele.webp"},
        {name: "Unstable Transmitter", sotv: false, sots: true, image: "images/itemsGreen/Unstable_Transmitter.webp"},
        {name: "War Horn", sotv: false, sots: false, image: "images/itemsGreen/War_Horn.webp"},
        {name: "Wax Quail", sotv: false, sots: false, image: "images/itemsGreen/Wax_Quail.webp"},
        {name: "Will-o'-the-wisp", sotv: false, sots: false, image: "images/itemsGreen/Will-o'-the-wisp.webp"}
    ],
    red: [
        {name: "57 Leaf Clover", sotv: false, sots: false, image: "images/itemsRed/57_Leaf_Clover.webp"},
        {name: "Aegis", sotv: false, sots: false, image: "images/itemsRed/Aegis.webp"},
        {name: "Alien Head", sotv: false, sots: false, image: "images/itemsRed/Alien_Head.webp"},
        {name: "Ben's Raincoat", sotv: true, sots: false, image: "images/itemsRed/Ben's_Raincoat.webp"},
        {name: "Bottled Chaos", sotv: true, sots: false, image: "images/itemsRed/Bottled_Chaos.webp"},
        {name: "Brainstalks", sotv: false, sots: false, image: "images/itemsRed/Brainstalks.webp"},
        {name: "Brilliant Behemoth", sotv: false, sots: false, image: "images/itemsRed/Brilliant_Behemoth.webp"},
        {name: "Ceremonial Dagger", sotv: false, sots: false, image: "images/itemsRed/Ceremonial_Dagger.webp"},
        {name: "Defensive Microbots", sotv: false, sots: false, image: "images/itemsRed/Defensive_Microbots.webp"},
        {name: "Dio's Best Friend", sotv: false, sots: false, image: "images/itemsRed/Dio's_Best_Friend.webp"},
        {name: "Electric Boomerang", sotv: false, sots: true, image: "images/itemsRed/Electric_Boomerang.webp"},
        {name: "Frost Relic", sotv: false, sots: false, image: "images/itemsRed/Frost_Relic.webp"},
        {name: "Growth Nectar", sotv: false, sots: true, image: "images/itemsRed/Growth_Nectar.webp"},
        {name: "H3AD-5T v2", sotv: false, sots: false, image: "images/itemsRed/H3AD-5T_v2.webp"},
        {name: "Happiest Mask", sotv: false, sots: false, image: "images/itemsRed/Happiest_Mask.webp"},
        {name: "Hardlight Afterburner", sotv: false, sots: false, image: "images/itemsRed/Hardlight_Afterburner.webp"},
        {name: "Interstellar Desk Plant", sotv: false, sots: false, image: "images/itemsRed/Interstellar_Desk_Plant.webp"},
        {name: "Item Scrap, Red", sotv: false, sots: false, image: "images/itemsRed/Item_Scrap,_Red.webp"},
        {name: "Laser Scope", sotv: true, sots: false, image: "images/itemsRed/Laser_Scope.webp"},
        {name: "N'kuhana's Opinion", sotv: false, sots: false, image: "images/itemsRed/N'kuhana's_Opinion.webp"},
        {name: "Pocket I.C.B.M.", sotv: true, sots: false, image: "images/itemsRed/Pocket_I.C.B.M..webp"},
        {name: "Rejuvenation Rack", sotv: false, sots: false, image: "images/itemsRed/Rejuvenation_Rack.webp"},
        {name: "Resonance Disc", sotv: false, sots: false, image: "images/itemsRed/Resonance_Disc.webp"},
        {name: "Runic Lens", sotv: false, sots: true, image: "images/itemsRed/Runic_Lens.webp"},
        {name: "Sentient Meat Hook", sotv: false, sots: false, image: "images/itemsRed/Sentient_Meat_Hook.webp"},
        {name: "Shattering Justice", sotv: false, sots: false, image: "images/itemsRed/Shattering_Justice.webp"},
        {name: "Sonorous Whispers", sotv: false, sots: true, image: "images/itemsRed/Sonorous_Whispers.webp"},
        {name: "Soulbound Catalyst", sotv: false, sots: false, image: "images/itemsRed/Soulbound_Catalyst.webp"},
        {name: "Spare Drone Parts", sotv: true, sots: false, image: "images/itemsRed/Spare_Drone_Parts.webp"},
        {name: "Symbiotic Scorpion", sotv: true, sots: false, image: "images/itemsRed/Symbiotic_Scorpion.webp"},
        {name: "Unstable Tesla Coil", sotv: false, sots: false, image: "images/itemsRed/Unstable_Tesla_Coil.webp"},
        {name: "Wake of Vultures", sotv: false, sots: false, image: "images/itemsRed/Wake_of_Vultures.webp"},
        {name: "War Bonds", sotv: false, sots: true, image: "images/itemsRed/War_Bonds.webp"}
    ],
    yellow: [
        {name: "Charged Perforator", sotv: false, sots: false, image: "images/itemsYellow/Charged_Perforator.webp"},
        {name: "Defense Nucleus", sotv: true, sots: false, image: "images/itemsYellow/Defense_Nucleus.webp"},
        {name: "Empathy Cores", sotv: false, sots: false, image: "images/itemsYellow/Empathy_Cores.webp"},
        {name: "Genesis Loop", sotv: false, sots: false, image: "images/itemsYellow/Genesis_Loop.webp"},
        {name: "Halcyon Seed", sotv: false, sots: false, image: "images/itemsYellow/Halcyon_Seed.webp"},
        {name: "Irradiant Pearl", sotv: false, sots: false, image: "images/itemsYellow/Irradiant_Pearl.webp"},
        {name: "Item Scrap, Yellow", sotv: false, sots: false, image: "images/itemsYellow/Item_Scrap,_Yellow.webp"},
        {name: "Little Disciple", sotv: false, sots: false, image: "images/itemsYellow/Little_Disciple.webp"},
        {name: "Mired Urn", sotv: false, sots: false, image: "images/itemsYellow/Mired_Urn.webp"},
        {name: "Molten Perforator", sotv: false, sots: false, image: "images/itemsYellow/Molten_Perforator.webp"},
        {name: "Pearl", sotv: false, sots: false, image: "images/itemsYellow/Pearl.webp"},
        {name: "Planula", sotv: false, sots: false, image: "images/itemsYellow/Planula.webp"},
        {name: "Queen's Gland", sotv: false, sots: false, image: "images/itemsYellow/Queen's_Gland.webp"},
        {name: "Shatterspleen", sotv: false, sots: false, image: "images/itemsYellow/Shatterspleen.webp"},
        {name: "Titanic Knurl", sotv: false, sots: false, image: "images/itemsYellow/Titanic_Knurl.webp"}
    ],
    lunar: [
        {name: "Brittle Crown", sotv: false, sots: false, image: "images/itemsLunar/Brittle_Crown.webp"},
        {name: "Corpsebloom", sotv: false, sots: false, image: "images/itemsLunar/Corpsebloom.webp"},
        {name: "Defiant Gouge", sotv: false, sots: false, image: "images/itemsLunar/Defiant_Gouge.webp"},
        {name: "Egocentrism", sotv: true, sots: false, image: "images/itemsLunar/Egocentrism.webp"},
        {name: "Essence of Heresy", sotv: false, sots: false, image: "images/itemsLunar/Essence_of_Heresy.webp"},
        {name: "Eulogy Zero", sotv: true, sots: false, image: "images/itemsLunar/Eulogy_Zero.webp"},
        {name: "Focused Convergence", sotv: false, sots: false, image: "images/itemsLunar/Focused_Convergence.webp"},
        {name: "Gesture of the Drowned", sotv: false, sots: false, image: "images/itemsLunar/Gesture_of_the_Drowned.webp"},
        {name: "Hooks of Heresy", sotv: false, sots: false, image: "images/itemsLunar/Hooks_of_Heresy.webp"},
        {name: "Light Flux Pauldron", sotv: true, sots: false, image: "images/itemsLunar/Light_Flux_Pauldron.webp"},
        {name: "Mercurial Rachis", sotv: false, sots: false, image: "images/itemsLunar/Mercurial_Rachis.webp"},
        {name: "Purity", sotv: false, sots: false, image: "images/itemsLunar/Purity.webp"},
        {name: "Shaped Glass", sotv: false, sots: false, image: "images/itemsLunar/Shaped_Glass.webp"},
        {name: "Strides of Heresy", sotv: false, sots: false, image: "images/itemsLunar/Strides_of_Heresy.webp"},
        {name: "Transcendence", sotv: false, sots: false, image: "images/itemsLunar/Transcendence.webp"},
        {name: "Visions of Heresy", sotv: false, sots: false, image: "images/itemsLunar/Visions_of_Heresy.webp"}
    ],
    voidWhite: [
        {name: "Encrusted Key", description: "Gain access to an Encrusted Cache that contains a void item. [purple:Corrupts all Rusted Keys.]", sotv: true, sots: false, image: "images/itemsVoid/Encrusted_Key.webp"},
        {name: "Lost Seer's Lenses", description: "Gain a 0.5% chance to instantly kill a non-boss enemy. [purple:Corrupts all Lens-Maker's Glasses.]", sotv: true, sots: false, image: "images/itemsVoid/Lost_Seer's_Lenses.webp"},
        {name: "Needletick", description: "Chance to collapse enemies on hit. [purple:Corrupts all Tri-Tip Daggers.]", sotv: true, sots: false, image: "images/itemsVoid/Needletick.webp"},
        {name: "Safer Spaces", description: "Block the next source of damage. [purple:Corrupts all Tougher Times.]", sotv: true, sots: false, image: "images/itemsVoid/Safer_Spaces.webp"},
        {name: "Weeping Fungus", description: "Heal while sprinting. [purple:Corrupts all Bustling Fungi.]", sotv: true, sots: false, image: "images/itemsVoid/Weeping_Fungus.webp"}
    ],
    voidGreen: [
        {name: "Voidsent Flame", description: "Full health enemies also detonate on hit. [purple:Corrupts all Will-o'-the-wisps.]", sotv: true, sots: false, image: "images/itemsVoid/Voidsent_Flame.webp"},
        {name: "Singularity Band", description: "High damage hits also create unstable black holes. Recharges over time. [purple:Corrupts all Runald's and Kjaro's Bands.]", sotv: true, sots: false, image: "images/itemsVoid/Singularity_Band.webp"},
        {name: "Polylute", description: "Chance to repeatedly strike a single enemy with lightning. [purple:Corrupts all Ukuleles.]", sotv: true, sots: false, image: "images/itemsVoid/Polylute.webp"},
        {name: "Plasma Shrimp", description: "While you have shield, fire missiles on every hit. [purple:Corrupts all AtG Missile Mk. 1s.]", sotv: true, sots: false, image: "images/itemsVoid/Plasma_Shrimp.webp"},
        {name: "Tentabauble", description: "Chance to root enemies on hit. [purple:Corrupts all Chronobaubles.]", sotv: true, sots: false, image: "images/itemsVoid/Tentabauble.webp"},
        {name: "Lysate Cell", description: "Add an extra charge of your Special skill. [purple:Corrupts all Fuel Cells.]", sotv: true, sots: false, image: "images/itemsVoid/Lysate_Cell.webp"}
    ],
    voidRed: [
        {name: "Pluripotent Larva", description: "Get a [purple:corrupted] extra life. Consumed on use. [purple:Corrupts all Dio's Best Friends.]", sotv: true, sots: false, image: "images/itemsVoid/Pluripotent_Larva.webp"},
        {name: "Benthic Bloom", description: "Upgrades your items at the start of each stage. [purple:Corrupts all 57 Leaf Clovers.]", sotv: true, sots: false, image: "images/itemsVoid/Benthic_Bloom.webp"}
    ],
    voidYellow: [
        {name: "Newly Hatched Zoea", description: "Periodically recruit allies from the [purple:Void]. [purple:Corrupts all] [yellowItems:yellow items.]", sotv: true, sots: false, image: "images/itemsVoid/Newly_Hatched_Zoea.webp"}
    ],
    equipment: [
        {name: "Blast Shower", sotv: false, sots: false, image: "images/itemsEquipment/Blast_Shower.webp"},
        {name: "Disposable Missile Launcher", sotv: false, sots: false, image: "images/itemsEquipment/Disposable_Missile_Launcher.webp"},
        {name: "Eccentric Vase", sotv: false, sots: false, image: "images/itemsEquipment/Eccentric_Vase.webp"},
        {name: "Executive Card", sotv: true, sots: false, image: "images/itemsEquipment/Executive_Card.webp"},
        {name: "Foreign Fruit", sotv: false, sots: false, image: "images/itemsEquipment/Foreign_Fruit.webp"},
        {name: "Forgive Me Please", sotv: false, sots: false, image: "images/itemsEquipment/Forgive_Me_Please.webp"},
        {name: "Fuel Array", sotv: false, sots: false, image: "images/itemsEquipment/Fuel_Array.webp"},
        {name: "Gnarled Woodsprite", sotv: false, sots: false, image: "images/itemsEquipment/Gnarled_Woodsprite.webp"},
        {name: "Goobo Jr.", sotv: true, sots: false, image: "images/itemsEquipment/Goobo_Jr..webp"},
        {name: "Gorag's Opus", sotv: false, sots: false, image: "images/itemsEquipment/Gorag's_Opus.webp"},
        {name: "Jade Elephant", sotv: false, sots: false, image: "images/itemsEquipment/Jade_Elephant.webp"},
        {name: "Milky Chrysalis", sotv: false, sots: false, image: "images/itemsEquipment/Milky_Chrysalis.webp"},
        {name: "Molotov (6-Pack)", sotv: true, sots: false, image: "images/itemsEquipment/Molotov_(6-Pack).webp"},
        {name: "Ocular HUD", sotv: false, sots: false, image: "images/itemsEquipment/Ocular_HUD.webp"},
        {name: "Preon Accumulator", sotv: false, sots: false, image: "images/itemsEquipment/Preon_Accumulator.webp"},
        {name: "Primordial Cube", sotv: false, sots: false, image: "images/itemsEquipment/Primordial_Cube.webp"},
        {name: "Radar Scanner", sotv: false, sots: false, image: "images/itemsEquipment/Radar_Scanner.webp"},
        {name: "Recycler", sotv: false, sots: false, image: "images/itemsEquipment/Recycler.webp"},
        {name: "Remote Caffeinator", sotv: true, sots: false, image: "images/itemsEquipment/Remote_Caffeinator.webp"},
        {name: "Royal Capacitor", sotv: false, sots: false, image: "images/itemsEquipment/Royal_Capacitor.webp"},
        {name: "Sawmerang", sotv: false, sots: false, image: "images/itemsEquipment/Sawmerang.webp"},
        {name: "Seed of Life", sotv: false, sots: true, image: "images/itemsEquipment/Seed_of_Life.webp"},
        {name: "Seed of Life (Consumed)", sotv: false, sots: true, image: "images/itemsEquipment/Seed_of_Life_(Consumed).webp"},
        {name: "Super Massive Leech", sotv: false, sots: false, image: "images/itemsEquipment/Super_Massive_Leech.webp"},
        {name: "The Back-up", sotv: false, sots: false, image: "images/itemsEquipment/The_Back-up.webp"},
        {name: "The Crowdfunder", sotv: false, sots: false, image: "images/itemsEquipment/The_Crowdfunder.webp"},
        {name: "Trophy Hunter's Tricorn", sotv: true, sots: false, image: "images/itemsEquipment/Trophy_Hunter's_Tricorn.webp"},
        {name: "Trophy Hunter's Tricorn (Consumed)", sotv: true, sots: false, image: "images/itemsEquipment/Trophy_Hunter's_Tricorn_(Consumed).webp"},
        {name: "Volcanic Egg", sotv: false, sots: false, image: "images/itemsEquipment/Volcanic_Egg.webp"}
    ],
    equipmentLunar: [
        {name: "Effigy of Grief", description: "Drop a permanent effigy that cripples ALL characters inside. Can place up to 5. ",sotv: false, sots: false, image: "images/itemsEquipmentLunar/Effigy_of_Grief.webp"},
        {name: "Glowing Meteorite", description: "Rain meteors from the sky, [red:hurting both enemies and allies.]",sotv: false, sots: false, image: "images/itemsEquipmentLunar/Glowing_Meteorite.webp"},
        {name: "Helfire Tincture", description: "Burn everything nearby... [red:including you and allies.]",sotv: false, sots: false, image: "images/itemsEquipmentLunar/Helfire_Tincture.webp"},
        {name: "Spinel Tonic", description: "Gain a massive boost to ALL stats. [red:Chance to gain an affliction that reduces ALL stats.]",sotv: false, sots: false, image: "images/itemsEquipmentLunar/Spinel_Tonic.webp"}
    ],
    equipmentElite: [
        {name: "Aurelionite's Blessing", description: "Become an aspect of radiance.",sotv: false, sots: true, image: "images/itemsEquipmentElite/Aurelionite's_Blessing.webp"},
        {name: "Her Biting Embrace", description: "Become an aspect of ice.",sotv: false, sots: false, image: "images/itemsEquipmentElite/Her_Biting_Embrace.webp"},
        {name: "His Reassurance", description: "Become an aspect of earth.",sotv: true, sots: false, image: "images/itemsEquipmentElite/His_Reassurance.webp"},
        {name: "His Spiteful Boon", description: "Become an aspect of spite.",sotv: false, sots: true, image: "images/itemsEquipmentElite/His_Spiteful_Boon.webp"},
        {name: "Ifrit's Distinction", description: "Become an aspect of fire.",sotv: false, sots: false, image: "images/itemsEquipmentElite/Ifrit's_Distinction.webp"},
        {name: "N'kuhana's Retort", description: "Become an aspect of corruption.",sotv: false, sots: false, image: "images/itemsEquipmentElite/N'kuhana's_Retort.webp"},
        {name: "Shared Design", description: "Become an aspect of perfection.",sotv: false, sots: false, image: "images/itemsEquipmentElite/Shared_Design.webp"},
        {name: "Silence Between Two Strikes", description: "Become an aspect of lightning.",sotv: false, sots: false, image: "images/itemsEquipmentElite/Silence_Between_Two_Strikes.webp"},
        {name: "Spectral Circlet", description: "Become an aspect of incorporeality.",sotv: false, sots: false, image: "images/itemsEquipmentElite/Spectral_Circlet.webp"}
    ],
    artifacts: [
        {name: "Chaos", description: "Friendly fire is enabled for both survivors and monsters alike.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Chaos.webp"},
        {name: "Command", description: "Choose your items.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Command.webp"},
        {name: "Death", description: "When one player dies, everyone dies. Enable only if you want to truly put your teamwork and individual skill to the ultimate test.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Death.webp"},
        {name: "Delusion", description: "Risk your items after completing the teleporter event in a test of memory to gain more items.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Delusion.webp"},
        {name: "Devotion", description: "Replace broken drones with Lemurian Eggs. Offer an item to gain followers.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Devotion.webp"},
        {name: "Dissonance", description: "Monsters can appear outside their usual environments.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Dissonance.webp"},
        {name: "Enigma", description: "Spawn with a random equipment that changes every time it's activated.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Enigma.webp"},
        {name: "Evolution", description: "Monsters gain items between stages.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Evolution.webp"},
        {name: "Frailty", description: "Fall damage is doubled and lethal.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Frailty.webp"},
        {name: "Glass", description: "Allies deal 500% damage, but have 10% health.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Glass.webp"},
        {name: "Honor", description: "Enemies can only spawn as elites.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Honor.webp"},
        {name: "Kin", description: "Monsters will be of only one type per stage.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Kin.webp"},
        {name: "Metamorphosis", description: "Players always spawn as a random survivor.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Metamorphosis.webp"},
        {name: "Rebirth", description: "Descend to Petrichor V with gifts from a previous life.", sotv: false, sots: true, image: "images/artifacts/Artifact_of_Rebirth.png"},
        {name: "Sacrifice", description: "Monsters drop items on death, but Chests no longer spawn.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Sacrifice.webp"},
        {name: "Soul", description: "Wisps emerge from defeated monsters.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Soul.webp"},
        {name: "Spite", description: "Enemies drop multiple exploding bombs on death.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Spite.webp"},
        {name: "Swarms", description: "Monster spawns are doubled, but monster maximum health is halved.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Swarms.webp"},
        {name: "Vengeance", description: "Your relentless doppelganger will invade every 10 minutes.", sotv: false, sots: false, image: "images/artifacts/Artifact_of_Vengeance.webp"}
    ]
};
